### ISSUE TITLE
Unable to build on windows

### ISSUE THREAD

**Issue by SuperPenguin** [schultek/jaspr#3]
```
PS C:\Users\andre\Desktop> jaspr create try_jaspr
Creating try_jaspr using template web-simple...

  .gitignore
  analysis_options.yaml
  CHANGELOG.md
  pubspec.yaml
  README.md
  web\index.html
  web\main.dart
  web\styles.css

  lib/app.dart
  lib/app.dart

Resolving dependencies...
Changed 81 dependencies!

Created project try_jaspr in try_jaspr! In order to get started, run the following commands:

  cd try_jaspr
  jaspr serve

PS C:\Users\andre\Desktop> cd try_jaspr
PS C:\Users\andre\Desktop\try_jaspr> jaspr build
Unhandled exception:
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2825:7)
#1      new Directory.fromUri (dart:io/directory.dart:129:59)
#2      BuildCommand.run (file:///C:/Users/andre/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/jaspr-0.1.2/bin/jaspr.dart:237:25)
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#5      new Future.sync (dart:async/future.dart:301:31)
#6      CommandRunner.run (package:args/command_runner.dart:119:14)
#7      main (file:///C:/Users/andre/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/jaspr-0.1.2/bin/jaspr.dart:23:31)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
Unhandled exception:
Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2825:7)
#1      new Directory.fromUri (dart:io/directory.dart:129:59)
#2      BuildCommand.run (file:///C:/Users/andre/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/jaspr-0.1.2/bin/jaspr.dart:237:25)
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#5      new Future.sync (dart:async/future.dart:301:31)
#6      CommandRunner.run (package:args/command_runner.dart:119:14)
#7      main (file:///C:/Users/andre/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/jaspr-0.1.2/bin/jaspr.dart:23:31)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
PS C:\Users\andre\Desktop\try_jaspr>
```

**Comment by SuperPenguin** [comment]
Seems this is the culprit
https://github.com/schultek/jaspr/blob/a33134e1177639505018413ee0c66f2fca504127/packages/jaspr/bin/jaspr.dart#L237

```dart
import 'dart:io';

void main(List<String> arguments) {
  final uri = Directory.current.uri;
  print(uri); // file:///C:/Users/andre/Desktop/New%20folder/hello/
  print(uri.scheme); // file
  final dir = Directory.fromUri(uri); // ok

  final uri2 = Uri.parse(Directory.current.path);
  print(uri2); // c:%5CUsers%5Candre%5CDesktop%5CNew%20folder%5Chello
  print(uri2.scheme); // c
  final dir2 = Directory.fromUri(uri2); // error
}
```

**Comment by schultek** [comment]
Thanks for investigating, this seems like an easy fix.

**Comment by schultek** [comment]
Fixed in version `0.1.3`
