### ISSUE TITLE
Invalid argument(s): A directory corresponding to fileSystemPath "...jaspr/experiments/minimal_app/lib/web" could not be found

### ISSUE THREAD

**Issue by MarkOSullivan94** [schultek/jaspr#37]
I've checked out `wip/v0.2` branch and whenever trying to run `main.dart` within the `lib` folder I end up seeing the following error.

```text
Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath ".../jaspr/experiments/minimal_app/lib/web" could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      staticFileHandler (package:jaspr/src/server/server_app.dart:273:7)
#2      staticFileHandler (package:jaspr/src/server/server_app.dart)
#3      _createHandler (package:jaspr/src/server/server_app.dart:278:38)
#4      ServerApp._run.<anonymous closure> (package:jaspr/src/server/server_app.dart:120:21)
#5      ServerApp._run.<anonymous closure> (package:jaspr/src/server/server_app.dart:117:22)
#6      new Future.microtask.<anonymous closure> (dart:async/future.dart:276:37)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

I've noticed this same issue on `master` branch and have moved the `main.dart` file up 1 directory so it is located at `...jaspr/experiments/minimal_app/main.dart` instead of `...jaspr/experiments/minimal_app/lib/main.dart` which lets me run the project although I'm not sure if there's a reason not to do this

**Comment by schultek** [comment]
Are you running the main.dart file directly? Because this wouldn't work. You should always use `jaspr serve`.

**Comment by MarkOSullivan94** [comment]
Yup I'm running the main.dart file directly, my bad!

Tried running it with `jaspr serve` and this is the result

```text
Starting jaspr development server...
The Dart VM service is listening on http://127.0.0.1:8181/EI7Tq9drx3w=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/EI7Tq9drx3w=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FEI7Tq9drx3w%3D%2Fws
lib/main.dart:1:8: Error: Error when reading '../../../../../.pub-cache/hosted/pub.dartlang.org/jaspr-0.1.5/lib/server.dart': No such file or directory
import 'package:jaspr/server.dart';
       ^
lib/app.dart:5:2: Error: Undefined name 'app'.
@app
 ^^^
lib/app.dart:5:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@app
 ^
lib/counter.dart:4:2: Error: Undefined name 'island'.
@island
 ^^^^^^
lib/counter.dart:4:2: Error: This can't be used as an annotation; an annotation should be a reference to a compile-time constant variable, or a call to a constant constructor.
@island
 ^
lib/main.dart:9:7: Error: Undefined name 'StyleRule'.
      StyleRule.import('https://fonts.googleapis.com/css?family=Roboto'),
      ^^^^^^^^^
lib/main.dart:11:40: Error: Undefined name 'Selector'.
        selector: const Selector.list([Selector.tag('html'), Selector.tag('body')]),
                                       ^^^^^^^^
lib/main.dart:11:49: Error: Method invocation is not a constant expression.
        selector: const Selector.list([Selector.tag('html'), Selector.tag('body')]),
                                                ^^^
lib/main.dart:11:62: Error: Undefined name 'Selector'.
        selector: const Selector.list([Selector.tag('html'), Selector.tag('body')]),
                                                             ^^^^^^^^
lib/main.dart:11:71: Error: Method invocation is not a constant expression.
        selector: const Selector.list([Selector.tag('html'), Selector.tag('body')]),
```

I initially thought that the `pubspec.yaml` for the example project might be outdated and that it might need to use the jaspr packages located within the repo and so I added this at the bottom of my `pubspec.yaml`

```yaml
dependency_overrides:
  jaspr:
    path: ../../packages/jaspr
  jaspr_builder:
    path: ../../packages/jaspr_builder
```

This resulted in the same error message as the opening post.

**Comment by schultek** [comment]
Yeah this seems to be some version mismatch with the new version.

Generally when not using the released version, better do `dart run jaspr serve` since this then uses the version defined for the project instead of the globally activated version.

And the `pubspec_overrides.yaml` should work when they point to the right paths, but only if you are on dart `>=2.17`.

**Comment by MarkOSullivan94** [comment]
I've now got the `minimal_app` launching! Thanks!

However when clicking on the buttons, they aren't doing anything. Want me to open a separate issue for this? What's the best way to debug this issue?

**Comment by schultek** [comment]
I don't think this makes sense, the experiments and example aren't all updated to the new version yet, It's still all work in progress.
