### ISSUE TITLE
`Text` component can broke an app

### ISSUE THREAD

**Issue by Maksimka101** [schultek/jaspr#7]
Hi, thanks for this package!

When the program is launched using `serve` command it breaks down with the exception below. However, it works fine when you `build` the app.

```dart
void main() {
  runApp(App());
}

class App extends StatelessComponent {
  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield Text('Hello World');
  }
}
```

Exception:
```
Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      _DomBuilder.text (package:domino/src/markup_impl.dart:177:28)
#2      TextElement.render (package:jaspr/src/framework/dom_component.dart:113:9)
#3      MultiChildElement.render (package:jaspr/src/framework/multi_child_element.dart:226:13)
#4      SingleChildElement.render (package:jaspr/src/framework/single_child_element.dart:64:13)
#5      BuildScheduler.render (package:jaspr/src/framework/components_binding.dart:75:11)
#6      renderMarkupIntoSink (package:domino/src/markup_impl.dart:33:12)
#7      renderMarkup (package:domino/src/markup_impl.dart:18:3)
#8      AppBinding.render (package:jaspr/src/bindings/server_bindings.dart:361:28)
<asynchronous suspension>
#9      renderHtml (package:jaspr/src/bindings/server_bindings.dart:318:14)
<asynchronous suspension>
```

**Comment by Maksimka101** [comment]
BTW it can be fixed by wrapping text in the `p` tag

```dart
class App extends StatelessComponent {
  @override
  Iterable<Component> build(BuildContext context) sync* {
    yield DomComponent(
      tag: "p",
      child: Text('Hello World'),
    );
  }
}
```

**Comment by schultek** [comment]
Yes, top level `Text` nodes are currently not possible, see this issue: [domino/issues/6](https://github.com/agilord/domino/issues/6)

**Comment by Maksimka101** [comment]
Hmm. Why does it work when you `build` the app?

**Comment by schultek** [comment]
It compiles, but when you run the app it has the same error.

**Comment by CodeDoctorDE** [comment]
Seems the author of the package does not reply...

**Comment by schultek** [comment]
Just as an update, I decided to completely redo the rendering implementation, mainly for performance reason. Currently wip, but after that I'm no longer depending on the domino package and this issue should be resolved.
