### ISSUE TITLE
fix: `jasper serve` does not work with Dart 3

### ISSUE THREAD

**Issue by exaby73** [schultek/jaspr#87]
**Description**

Using Dart 3, `jaspr serve` throws an error

**Steps To Reproduce**

- Create a new Jaspr app with Dart 3
- Run `jaspr serve` and notice the error.

**Expected Behavior**

Jaspr should build and serve the app

**Additional Context**

Full error logs of `jaspr serve -v`:

```console
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[SEVERE] Unhandled exception:
[SEVERE] Invalid argument(s): Required input cycle for [{autoApply: AutoApply.dependents, import: package:jaspr_builder/builder.dart, builderFactories: [buildApps], buildExtensions: {^lib/{{file}}.dart: [lib/{{file}}.g.dart, web/{{file}}.app.dart, web/{{file}}.island.dart]}, requiredInputs: [], runsBefore: [jaspr_builder:apps, build_web_compilers:build_web_compilers], isOptional: false, buildTo: BuildTo.source, defaults: Instance of 'TargetBuilderConfigDefaults'}]
[SEVERE] #0      findBuilderOrder (package:build_runner/src/build_script_generate/builder_ordering.dart:32:5)
[SEVERE] #1      findBuildScriptOptions (package:build_runner/src/build_script_generate/build_script_generate.dart:137:7)
[SEVERE] <asynchronous suspension>
[SEVERE] #2      _generateBuildScript (package:build_runner/src/build_script_generate/build_script_generate.dart:32:16)
[SEVERE] <asynchronous suspension>
[SEVERE] #3      logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:18)
[SEVERE] <asynchronous suspension>
[SEVERE] #4      generateAndRun (package:build_runner/src/build_script_generate/bootstrap.dart:60:25)
[SEVERE] <asynchronous suspension>
[SEVERE] #5      main (file:///Users/nabeelparkar/.pub-cache/hosted/pub.dev/build_runner-2.4.4/bin/build_runner.dart:99:24)
[SEVERE] <asynchronous suspension>
Bad state: Unable to start build daemon.
```

**Comment by RossComputerGuy** [comment]
Same here.

`dart --version`: `Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on "linux_x64"`
Jaspr version: `0.3.0`

**Comment by schultek** [comment]
Hi. Unfortunately I currently don't have a lot of time to look at this, but I'm happy to review PRs.

**Comment by schultek** [comment]
Fixed in v0.4.0

**Comment by CodeDoctorDE** [comment]
Thank you for creating this wonderful package.
It helps me very much creating wonderful interacting websites that also works without enabling javascript!
